{
 "title": "Database",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "delta",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "query",
    "query": "label_values(app_repository_query_duration_seconds_count, query)"
   }
  ]
 },
 "panels": [
  { "title": "$query", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "query" },
  {
   "title": "Calls",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(app_repository_query_duration_seconds_bucket{query=\"$query\"}[$delta])) by (query)",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Average Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(app_repository_query_duration_seconds_sum{query=\"$query\"}[$delta])) / sum(rate(app_repository_query_duration_seconds_count{query=\"$query\"}[$delta]))",
     "legendFormat": "average"
    }
   ]
  },
  {
   "title": "Quantiles",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.25, sum(rate(app_repository_query_duration_seconds_bucket{query=\"$query\"}[$delta])) by (le))",
     "legendFormat": "25th"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(app_repository_query_duration_seconds_bucket{query=\"$query\"}[$delta])) by (le))",
     "legendFormat": "50th"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(app_repository_query_duration_seconds_bucket{query=\"$query\"}[$delta])) by (le))",
     "legendFormat": "75th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(app_repository_query_duration_seconds_bucket{query=\"$query\"}[$delta])) by (le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(app_repository_query_duration_seconds_bucket{query=\"$query\"}[$delta])) by (le))",
     "legendFormat": "99th"
    }
   ]
  },
  { "title": "$query", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Calls",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(app_repository_query_duration_seconds_bucket{query=\"$query\"}[$delta])) by (query)",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Average Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(app_repository_query_duration_seconds_sum{query=\"$query\"}[$delta])) / sum(rate(app_repository_query_duration_seconds_count{query=\"$query\"}[$delta]))",
     "legendFormat": "average"
    }
   ]
  },
  {
   "title": "Quantiles",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.25, sum(rate(app_repository_query_duration_seconds_bucket{query=\"$query\"}[$delta])) by (le))",
     "legendFormat": "25th"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(app_repository_query_duration_seconds_bucket{query=\"$query\"}[$delta])) by (le))",
     "legendFormat": "50th"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(app_repository_query_duration_seconds_bucket{query=\"$query\"}[$delta])) by (le))",
     "legendFormat": "75th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(app_repository_query_duration_seconds_bucket{query=\"$query\"}[$delta])) by (le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(app_repository_query_duration_seconds_bucket{query=\"$query\"}[$delta])) by (le))",
     "legendFormat": "99th"
    }
   ]
  },
  { "title": "$query", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Calls",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(app_repository_query_duration_seconds_bucket{query=\"$query\"}[$delta])) by (query)",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Average Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(app_repository_query_duration_seconds_sum{query=\"$query\"}[$delta])) / sum(rate(app_repository_query_duration_seconds_count{query=\"$query\"}[$delta]))",
     "legendFormat": "average"
    }
   ]
  },
  {
   "title": "Quantiles",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.25, sum(rate(app_repository_query_duration_seconds_bucket{query=\"$query\"}[$delta])) by (le))",
     "legendFormat": "25th"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(app_repository_query_duration_seconds_bucket{query=\"$query\"}[$delta])) by (le))",
     "legendFormat": "50th"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(app_repository_query_duration_seconds_bucket{query=\"$query\"}[$delta])) by (le))",
     "legendFormat": "75th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(app_repository_query_duration_seconds_bucket{query=\"$query\"}[$delta])) by (le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(app_repository_query_duration_seconds_bucket{query=\"$query\"}[$delta])) by (le))",
     "legendFormat": "99th"
    }
   ]
  },
  { "title": "$query", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Calls",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(app_repository_query_duration_seconds_bucket{query=\"$query\"}[$delta])) by (query)",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Average Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(app_repository_query_duration_seconds_sum{query=\"$query\"}[$delta])) / sum(rate(app_repository_query_duration_seconds_count{query=\"$query\"}[$delta]))",
     "legendFormat": "average"
    }
   ]
  },
  {
   "title": "Quantiles",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.25, sum(rate(app_repository_query_duration_seconds_bucket{query=\"$query\"}[$delta])) by (le))",
     "legendFormat": "25th"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(app_repository_query_duration_seconds_bucket{query=\"$query\"}[$delta])) by (le))",
     "legendFormat": "50th"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(app_repository_query_duration_seconds_bucket{query=\"$query\"}[$delta])) by (le))",
     "legendFormat": "75th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(app_repository_query_duration_seconds_bucket{query=\"$query\"}[$delta])) by (le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(app_repository_query_duration_seconds_bucket{query=\"$query\"}[$delta])) by (le))",
     "legendFormat": "99th"
    }
   ]
  },
  { "title": "$query", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Calls",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(app_repository_query_duration_seconds_bucket{query=\"$query\"}[$delta])) by (query)",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Average Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(app_repository_query_duration_seconds_sum{query=\"$query\"}[$delta])) / sum(rate(app_repository_query_duration_seconds_count{query=\"$query\"}[$delta]))",
     "legendFormat": "average"
    }
   ]
  },
  {
   "title": "Quantiles",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.25, sum(rate(app_repository_query_duration_seconds_bucket{query=\"$query\"}[$delta])) by (le))",
     "legendFormat": "25th"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(app_repository_query_duration_seconds_bucket{query=\"$query\"}[$delta])) by (le))",
     "legendFormat": "50th"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(app_repository_query_duration_seconds_bucket{query=\"$query\"}[$delta])) by (le))",
     "legendFormat": "75th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(app_repository_query_duration_seconds_bucket{query=\"$query\"}[$delta])) by (le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(app_repository_query_duration_seconds_bucket{query=\"$query\"}[$delta])) by (le))",
     "legendFormat": "99th"
    }
   ]
  },
  { "title": "$query", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Calls",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(app_repository_query_duration_seconds_bucket{query=\"$query\"}[$delta])) by (query)",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Average Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 31 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(app_repository_query_duration_seconds_sum{query=\"$query\"}[$delta])) / sum(rate(app_repository_query_duration_seconds_count{query=\"$query\"}[$delta]))",
     "legendFormat": "average"
    }
   ]
  },
  {
   "title": "Quantiles",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 31 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.25, sum(rate(app_repository_query_duration_seconds_bucket{query=\"$query\"}[$delta])) by (le))",
     "legendFormat": "25th"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(app_repository_query_duration_seconds_bucket{query=\"$query\"}[$delta])) by (le))",
     "legendFormat": "50th"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(app_repository_query_duration_seconds_bucket{query=\"$query\"}[$delta])) by (le))",
     "legendFormat": "75th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(app_repository_query_duration_seconds_bucket{query=\"$query\"}[$delta])) by (le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(app_repository_query_duration_seconds_bucket{query=\"$query\"}[$delta])) by (le))",
     "legendFormat": "99th"
    }
   ]
  },
  { "title": "$query", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Calls",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(app_repository_query_duration_seconds_bucket{query=\"$query\"}[$delta])) by (query)",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Average Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 37 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(app_repository_query_duration_seconds_sum{query=\"$query\"}[$delta])) / sum(rate(app_repository_query_duration_seconds_count{query=\"$query\"}[$delta]))",
     "legendFormat": "average"
    }
   ]
  },
  {
   "title": "Quantiles",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 37 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.25, sum(rate(app_repository_query_duration_seconds_bucket{query=\"$query\"}[$delta])) by (le))",
     "legendFormat": "25th"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(app_repository_query_duration_seconds_bucket{query=\"$query\"}[$delta])) by (le))",
     "legendFormat": "50th"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(app_repository_query_duration_seconds_bucket{query=\"$query\"}[$delta])) by (le))",
     "legendFormat": "75th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(app_repository_query_duration_seconds_bucket{query=\"$query\"}[$delta])) by (le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(app_repository_query_duration_seconds_bucket{query=\"$query\"}[$delta])) by (le))",
     "legendFormat": "99th"
    }
   ]
  },
  { "title": "$query", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Calls",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(app_repository_query_duration_seconds_bucket{query=\"$query\"}[$delta])) by (query)",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Average Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 43 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(app_repository_query_duration_seconds_sum{query=\"$query\"}[$delta])) / sum(rate(app_repository_query_duration_seconds_count{query=\"$query\"}[$delta]))",
     "legendFormat": "average"
    }
   ]
  },
  {
   "title": "Quantiles",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 43 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.25, sum(rate(app_repository_query_duration_seconds_bucket{query=\"$query\"}[$delta])) by (le))",
     "legendFormat": "25th"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(app_repository_query_duration_seconds_bucket{query=\"$query\"}[$delta])) by (le))",
     "legendFormat": "50th"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(app_repository_query_duration_seconds_bucket{query=\"$query\"}[$delta])) by (le))",
     "legendFormat": "75th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(app_repository_query_duration_seconds_bucket{query=\"$query\"}[$delta])) by (le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(app_repository_query_duration_seconds_bucket{query=\"$query\"}[$delta])) by (le))",
     "legendFormat": "99th"
    }
   ]
  }
 ]
}