{
 "title": "Overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "delta",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "api", "query": "app_flask_http_request_total" }
  ]
 },
 "panels": [
  {
   "title": "Todos",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(app_current_todos) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Flask HTTP Calls",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(app_flask_http_request_total[$delta])) by (status_code)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Average Query Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(app_repository_query_duration_seconds_sum[$delta])) by (query) /\nsum(rate(app_repository_query_duration_seconds_count[$delta])) by (query)",
     "legendFormat": "{{query}}"
    }
   ]
  }
 ]
}